language: ruby
script:   bundle exec rake test
cache:    bundler
sudo:     false

before_install:
  - gem i bundler -v=1.9.4

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-1.7.19
  - jruby-head
  - rbx-2.4.1
  - rbx-2.5.2

gemfile:
  - gemfiles/activerecord_32.gemfile
  - gemfiles/activerecord_40.gemfile
  - gemfiles/activerecord_41.gemfile
  - gemfiles/activerecord_42.gemfile
  - gemfiles/activerecord_edge.gemfile
